# https://medium.com/starbugs/3dd2d70eeb
# https://github.com/peaceiris/actions-gh-pages
name: fetch-laptop-spec-then-build

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  pull_request:
  schedule:
    - cron: '0 */24 * * * ' # update every 24 hours
  workflow_dispatch: # Allow manual trigger from GitHub UI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: fetch laptop data
        run: pnpm crawler

      - name: Build
        run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
