# https://medium.com/starbugs/3dd2d70eeb
# https://github.com/peaceiris/actions-gh-pages
name: fetch-laptop-spec-then-build

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  pull_request:
  schedule:
    - cron: '0 */24 * * * ' # update every 24 hours

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: npm install

      - name: fetch laptop data
        run: node crawler.js

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
